model_type: svm
model_hyperparams:
# LinearSVC
  penalty: 
  - l1
  - l2
  loss: squared_hinge
  dual: False
  tol: 1e-3
  C: 
  - 0.1
  - 1.0
  - 10.0
  multi_class: ovr
  fit_intercept: True
  intercept_scaling: 1
  class_weight: balanced
  # verbose: 0
  # random_state: 42 # not used when dual=False
  max_iter: 500
# CalibratedClassifierCV
  method: sigmoid
  cv: 5
  n_jobs: 5 # if parallelize_labels = 14, uses 70 total processes
  ensemble: False
standard_scale: True