model_type: xgb
model_hyperparams:
# XGBClassifier
  booster: gbtree
  tree_method: hist
  random_state: 42
  n_jobs: 5 # if parallelize_labels = 14, uses 70 total processes
  verbosity: 0
  objective: "binary:logistic"
  eval_metric: logloss
  early_stopping_rounds: 3
  n_estimators:
  - 100
  - 200
  - 400
  learning_rate:
  - 0.03
  - 0.1
  - 0.3
  max_depth:
  - 3
  - 6
  - 10
  min_child_weight: 1
  gamma: 0
  subsample: 0.8
  colsample_bytree: 0.8
  scale_pos_weight: 10 # can't automatically set to inverse prevalence
  reg_alpha: 0 # l1 reg
  reg_lambda: 1 # l2 reg
standard_scale: True