name: cxrmate
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.13
  - pip:
      - pandas==2.1.3
      - torch==2.4.0
      - torchvision==0.19.0
      - transformers==4.40.2
      - datasets==2.20.0
      - timm==1.0.7
      - einops==0.8.0
