name: cxrrepair
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.13
  - pip:
      - torch==2.4.0
      - torchvision==0.19.0
      - pandas==2.1.3
      - scikit-learn==1.5.1
      - h5py==3.11.0
      - tqdm==4.66.4
      - ftfy==6.3.1
      - regex==2024.11.6
      - nltk==3.9.1
      - pillow==9.5.0
